apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1

  selector:
    matchLabels:
      app: authentication

  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: "uc4official/authentication_service:latest"
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx256m -Dconfig.resource=prod-application.conf"
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: authentication-application-secret
                  key: secret
            - name: POSTGRESQL_URL
              value: "jdbc:postgresql://postgres/uc4authentication"
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-authentication
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-authentication
                  key: password
            - name: KAFKA_SERVICE_NAME
              value: "_tcp-clients._tcp.strimzi-kafka-brokers.kafka"
            - name: REQUIRED_CONTACT_POINT_NR
              value: "1"
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 0.25
              memory: 512M
          ports:
            - name: management
              containerPort: 8558
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: authentication
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: authentication