apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: course
spec:
  replicas: 1

  selector:
    matchLabels:
      app: course

  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
        - name: course
          image: "uc4official/course_service:latest"
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx256m -Dconfig.resource=prod-application.conf"
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: course-application-secret
                  key: secret
            - name: CASSANDRA_SERVICE_NAME
              value: "_cql._tcp.cassandra"
            - name: KAFKA_SERVICE_NAME
              value: "_clients._tcp.strimzi-kafka-brokers"
            - name: REQUIRED_CONTACT_POINT_NR
              value: "1"
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 0.25
              memory: 512M
          ports:
            - name: management
              containerPort: 8558
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: course
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app: course
  type: LoadBalancer