version: '3.1'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
    ports:
      - "5432:5432"
  nginx:
    image: nginx:latest
    container_name: imagenginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/images:/data/images
    ports:
      - "9050:80"