version: '3.2'
services:
  postgres:
    image: uc4official/postgres:latest
    container_name: postgres
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
    volumes:
      - ./docker/postgres.conf:/uc4/postgresql.conf
    ports:
      - "5432:5432"
      
  imaginary:
    image: h2non/imaginary:latest
    container_name: imaginary
    environment:
       PORT: 9000
    command: -cors -disable-endpoints form
    ports:
      - "9020:9000"
      