kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: worker
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 9002
  - containerPort: 30080
    hostPort: 9081
  - containerPort: 30443
    hostPort: 9444