apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 3

  selector:
    matchLabels:
      app: authentication

  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: "uc4official/authentication_service:latest"
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx256m -Dconfig.resource=prod-application.conf"
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: authentication-application-secret
                  key: secret
            - name: KAFKA_SERVICE_NAME
              value: "_clients._tcp.strimzi-kafka-brokers"
            - name: REQUIRED_CONTACT_POINT_NR
              value: "3"
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 0.25
              memory: 512M
          ports:
            - name: management
              containerPort: 8558
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: authentication
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app: authentication
  type: LoadBalancer
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---