apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: course
spec:
  selector:
    matchLabels:
      app: course

  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
        - name: course
          image: "course:latest"
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx256m -Dconfig.resource=prod-application.conf"
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 0.25
              memory: 512Mi

  - name: APPLICATION_SECRET
    value: "test"
  - name: KAFKA_SERVICE_NAME
    value: "_clients._tcp.strimzi-kafka-brokers"
---
apiVersion: v1
kind: Service
metadata:
  name: course
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app: course
  type: LoadBalancer
