apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"