apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: service-routes
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/course-management`)
      kind: Rule
      services:
        - name: course
          port: 80
    - match: PathPrefix(`/user-management`)
      kind: Rule
      services:
        - name: user
          port: 80
    - match: PathPrefix(`/hl-course-management`)
      kind: Rule
      services:
        - name: hlcourse
          port: 80
    - match: PathPrefix(`/authentication-management`)
      kind: Rule
      services:
        - name: authentication
          port: 80
