name: Lagom Test Pipeline

on:
  push:
    branches:
      - '**lagom**'
      - develop
      - master
  pull_request:
    branches: 
      - develop
      - master

jobs:
  RunAllTests:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out source repository
      uses: actions/checkout@v2
    
    # Set up JDK
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Start postgresql docker
    - name: Start Postgres
      run: |
        pushd ./product_code/lagom
        docker-compose up -d
        sleep 30
        popd

    #change .sbtopts
    - name: Add -J to .sbtops
      run: |
        pushd ./product_code/lagom
        echo "-J-Xms512M -J-Xmx4096M -J-Xss2M -J-XX:MaxMetaspaceSize=1024M" > .sbtopts
        popd
    
    # run sbt tests
    - name: Run tests
      run: |
        pushd ./product_code/lagom
        echo "##################################"
        echo "#  Starting Tests with Coverage  #"
        echo "##################################"
        sbt test coverageReport coverageAggregate 
        popd
        
    - name: Scalatest multiproject HTML merger
      uses: bastihav/scalatest-multiproject-html-action@v1
      with:
        path: product_code/lagom/target/test_reports/

        
    - name: Upload test report
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: test-reports
        path: product_code/lagom/target/test_reports/
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: code-coverage
        path: product_code/lagom/target/scala-2.13/scoverage-report