name: Lagom Test Pipeline

on:
  pull_request:
    branches: [ develop ]

jobs:
  RunAllTests:

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out source repository
      uses: actions/checkout@v2
    
    # Set up JDK
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Start postgresql docker
    - name: Start Postgres
      run: |
        pushd ./product_code/lagom
        docker-compose up -d
        sleep 30
        popd

    #change .sbtopts
    - name: Add -J to .sbtops
      run: |
        pushd ./product_code/lagom
        echo "-J-Xms512M -J-Xmx4096M -J-Xss2M -J-XX:MaxMetaspaceSize=1024M" > .sbtopts
        popd
    
    # run sbt tests
    - name: Run tests
      run: |
        pushd ./product_code/lagom
        echo "##########################"
        echo "#    starting test       #"
        echo "##########################"
        sbt test
        popd