name: Lagom Deployment Pipeline

on: [push]

jobs:
  check:
    name: Check code format

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out source repository
      uses: actions/checkout@v2
        
    # Set up JDK
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    #change .sbtopts
    - name: Add -J to .sbtops
      run: |
        pushd ./product_code/lagom
        echo "-J-Xms512M -J-Xmx4096M -J-Xss2M -J-XX:MaxMetaspaceSize=1024M" > .sbtopts
        popd
    
    # run scalariform test
    - name: Code format check
      run: |
        pushd ./product_code/lagom
        echo "##########################"
        echo "#    Check Code Style    #"
        echo "##########################"
        wget https://github.com/scala-ide/scalariform/releases/download/0.2.10/scalariform.jar
        java -jar scalariform.jar --preferenceFile=".scalariform.conf" --test --recurse .
        popd