name: Lagom Manual Deployment Pipeline

on:
  # manual triggers with parameters
  workflow_dispatch:
    inputs:
        target_service:
            description: "The name of the service which should get published"
            required: true

jobs:
  deploy:
    name: Deploy to DockerHub

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out source repository
      uses: actions/checkout@v2
        
    # Set up JDK
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    #change .sbtopts
    - name: Add -J to .sbtops
      run: |
        pushd ./product_code
        echo "-J-Xms512M -J-Xmx4096M -J-Xss2M -J-XX:MaxMetaspaceSize=1024M" > .sbtopts
        popd

    #check dependencies
    - name: Dependency check
      id: dependency-check
      run: | 
        pushd ./product_code
        echo "##########################"
        echo "#   check dependencies   #"
        echo "##########################"
        service=${{ github.event.inputs.target_service }}
        if sbt "dependencyCheck ${service}"
        then
          echo "::set-output name=FAILURE::0"
        else
          echo "::set-output name=FAILURE::1"
          message=`cat target/dependencyCheck.txt`
          message="${message//'%'/'%25'}"
          message="${message//$'\n'/'%0A'}"
          message="${message//$'\r'/'%0D'}"
          echo "::set-output name=MESSAGE::$message"
          echo "::set-output name=SERVICE::${service^} Service (v?.?.?)"
        fi
        popd
      
    - name: Discord notification
      if: ${{ steps.dependency-check.outputs.FAILURE != 0 }}
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: warn
        username: ${{ steps.dependency-check.outputs.SERVICE }}
        color: '#FFFF00'
        avatarUrl: https://pm.uni-paderborn.de/_Resources/Persistent/Thumbnails/310x443/66173.png
        description: ${{ steps.dependency-check.outputs.MESSAGE }}
        details: ''
        footer: ''
        text: Following services could be broken by a breaking change.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

    
    # run sbt docker publish
    - name: Deploy
      run: |
        pushd ./product_code
        echo "##########################"
        echo "    deploy ${{ github.event.inputs.target_service }}   "
        echo "##########################"
        sbt ${{ github.event.inputs.target_service }}_service/docker:publish
        popd
