name: Lagom Deployment Pipeline

on:
  push:
    tags:
      - v0
      - v1

jobs:
  deploy:
    name: Deploy to DockerHub

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out source repository
      uses: actions/checkout@v2
    
    # Set up Node
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
        
    # Set up JDK
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    #change .sbtopts
    - name: Add -J to .sbtops
      run: |
        pushd ./product_code/lagom
        echo "-J-Xms512M -J-Xmx4096M -J-Xss2M -J-XX:MaxMetaspaceSize=1024M" > .sbtopts
        popd
    
    # run sbt docker publish
    - name: Deploy
      run: |
        pushd ./product_code/lagom
        echo "##########################"
        echo "#   deploy services      #"
        echo "##########################"
        sbt authentication_service/docker:publish
        sbt user_service/docker:publish
        sbt course_service/docker:publish
        sbt hyperledger_service/docker:publish
        sbt hl_course_service/docker:publish
        popd